# fly.toml file generated for hero-tactics-game-backend

app = "hero-tactics-game-backend"
primary_region = "gru"  # São Paulo, Brazil

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Websocket specific settings
  [http_service.tcp_options]
    keepalive = 300  # Keep connections alive for 5 minutes

  # Health check settings
  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false
    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

